### ISSUE TITLE
How to use address_normalizer?

### ISSUE THREAD

**Issue by migurski** [openvenues/address_normalizer#2]
I’m not entirely sure what to do with it.

```
>>> import address_normalizer as an
>>> help(an)

>>> dir(an)
['__builtins__', '__doc__', '__file__', '__name__', '__package__', '__path__']
>>> help(an)

>>> from address_normalizer import utils
>>> help(utils)

>>> from address_normalizer import text
>>> help(text)

>>> text.normalize('123 main st')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'normalize'
>>> help(text)

>>> from address_normalizer.text import normalize
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "address_normalizer/text/normalize.py", line 18, in <module>
    from address_normalizer.text.tokenize import *
  File "address_normalizer/text/tokenize.py", line 7, in <module>
    from address_normalizer.text import _scanner
ImportError: cannot import name _scanner
```

**Comment by thatdatabaseguy** [comment]
Yep, that is confusing indeed. Refactored a bit, added some convenience methods and a usage example. Try:

```
from address_normalizer import normalize_street_address

addr1 = normalize_street_address('30 West Twenty-sixth Street Floor Number 7')
addr2 = normalize_street_address('30 W 26th St Fl #7')

# Share at least one expansion in common
addr1 & addr2
```

If you see "ImportError: cannot import name _scanner" again, let me know. That sounds like perhaps the C extension didn't build properly or there's some path issue. If you can send me your Python/OS version, the command you used to install and maybe the stdout from said command I can attempt to diagnose.

**Comment by migurski** [comment]
Here’s a three-part log of my install process: https://gist.github.com/migurski/aac61d6e12f8da5dea9c

**Comment by thatdatabaseguy** [comment]
Thanks for the detailed report!

Seeing this now. The short answer is I mistakenly left out the protocol in the command for pip installing from github. Should have been ```pip install git+https://github.com/openvenues/address_normalizer``` and this issue would have avoided altogether.

In the case of cloning the repo first as in that log, the fix is ```cd ..``` (or anywhere else really) before running the Python interpreter. Python's module search path is: builtins, current directory, then PYTHONPATH. In that log you were still in /tmp/an, so when the interpreter gets the statement ```from address_normalizer import normalize_street_address```, it sees a module named address_normalizer in the current directory and tries to import that. In this case the downloaded code hasn't built the C extension, whereas the installed version has.

**Comment by migurski** [comment]
:boom: that worked :boom:
